Qual a diferença entre uma variável tipo int e uma tipo float?

In [ ]:
# O tipo int trata de números inteiros e não aceitam números decimais
# Já o tipo float aceita números decimais que possuem virgulas

O que é uma variável do tipo string?

In [ ]:
# a variável conhecida como string de abreviação str é em suma uma variável de texto utilizada para diferenciar quando
# uma é variável númerica ou de texto, números tambem são aceitos como string.

In [6]:
def maior_numero(): 

    a = input("Digite o primeiro número: ")
    b = input("Digite o segundo número: ")
    c = input("Digite o terceiro número: ")

    if a>b and a>c:
        print(f"O maior número é {a}")
    elif b>a and b>c:
        print(f"O maior número é {b}")
    else:
        print(f"O maior número é {c}")

maior_numero()

O maior número é 3


Crie uma função que identifique se duas ou mais palavras inseridas pelo usuário são anagramas.

In [7]:
def anagrama_check():

    palavra_1 = input("Escreva uma palavra: ")
    palavra_2 = input("Escreva uma segunda palavra: ")

    if (sorted(palavra_1) == sorted(palavra_2)):
        print(f"As palavras {palavra_1} e {palavra_2} são anagramas")
    else:
        print("As palavras não são anagramas")

anagrama_check()

As palavras banana e ananab são anagramas


Crie uma função que retorne a contagem de consoantes e vogais de uma palavra imputada pelo usuário.

In [9]:
def contagem_letras():

    palavra = input("Digite uma palavra: ")
    palavra_min = palavra.lower()
    vogais = 0
    consoantes = 0

    for letra in palavra_min:
        if letra in "a, e, i, o, u":
            vogais = vogais + 1
        else:
            consoantes = consoantes + 1

    print(f"A palavra {palavra} tem o total de {vogais} vogais e {consoantes} consoantes")

contagem_letras()

A palavra minguante tem o total de 4 vogais e 5 consoantes


O que são dicionários em Python?

In [12]:
# os dicionários são estrututras que possuem uma coleção de itens e seus elementos, esses elementos possuem uma chave e um valor
# tem como tipo dict e é delimitado pelo simbolo {}  

dicionario = {'chave': 1, 'chave 2': 2}
type(dicionario)

dict

Crie uma lista com os 100 mil primeiros números naturais na sequência (i.e., de 1 à 100000). Salve esta lista em um objeto com nome cem_mil_lista. Inicie então uma lista vazia chamada numeros_pares. A partir da lista cem_mil_lista, salve todos os valores pares na lista numeros_pares. Resolva este exercício de duas formas: a primeira utilizando um loop com o for e a segunda com list comprehension. Compare o tempo de execução das duas.

In [8]:
%%time
cem_mil_lista = list(range(0, 100000))
numeros_pares = []

def separa_par():
    for x in cem_mil_lista:
        if x % 2 == 0:
           numeros_pares.append(x)

separa_par() 


 

Wall time: 17 ms


In [5]:
numeros_pares

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [9]:
%%time
cem_mil_lista = list(range(0, 100000))
numeros_pares_2 = [x for x in cem_mil_lista if x % 2 == 0]


Wall time: 15 ms


In [7]:
numeros_pares_2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

Para que serve o argumento Kwargs nas funções?

In [12]:
# o argumento Kwargs é a abreviação de keyword arguments e é usado geralmente para passar um dicionário com várias chaves(keys)
# para uma determinada função 

def func_kwargs(**kwargs):
    print(f'tipo: {type(kwargs)} conteudo: {kwargs}')
    for key, value in kwargs.items():
        print(f'atributo: {key}, valor: {value}')

func_kwargs(nome='Caio', sobrenome = 'Bolognese', idade = 21)

tipo: <class 'dict'> conteudo: {'nome': 'Caio', 'sobrenome': 'Bolognese', 'idade': 21}
atributo: nome, valor: Caio
atributo: sobrenome, valor: Bolognese
atributo: idade, valor: 21


Escreva um programa em Python para encontrar os números que são divisíveis por 7 e múltiplos de 5, entre 1500 e 2700 (ambos incluídos). Em outras palavras, combine o que você aprendeu de loop e condicional para criar uma lista de valores que atendam às condições exigidas.

In [59]:
lista_numeros = list(range(1500, 2701))
numeros_selecionados = []

In [60]:
def seleciona_numeros():
    for x in lista_numeros:
        if x % 7 == 0 and x % 5 == 0:
            numeros_selecionados.append(x)

seleciona_numeros()

             

In [61]:
numeros_selecionados


[1505,
 1540,
 1575,
 1610,
 1645,
 1680,
 1715,
 1750,
 1785,
 1820,
 1855,
 1890,
 1925,
 1960,
 1995,
 2030,
 2065,
 2100,
 2135,
 2170,
 2205,
 2240,
 2275,
 2310,
 2345,
 2380,
 2415,
 2450,
 2485,
 2520,
 2555,
 2590,
 2625,
 2660,
 2695]

Escreva um programa Python para construir o padrão a seguir, usando um número de loop aninhado.

In [1]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]

for x in lista: 
    if x == 1:
        print('1')
    if x == 2:
        print('22')
    if x == 3:
        print('333')
    if x == 4:
        print('4444')
    if x == 5:
        print('55555')
    if x == 6:
        print('666666')
    if x == 7:
        print('7777777')
    if x == 8:
        print('88888888')
    if x == 9:
        print('999999999')

1
22
333
4444
55555
666666
7777777
88888888
999999999


Escreva um programa em Python para verificar se um alfabeto é uma vogal ou uma consoante.

In [8]:
vogais = ['a', 'e', 'i', 'o', 'u']
def verifica_alfabeto():
    letra = input('Insira uma letra do alfabeto: ')
    if letra in vogais:
        print(f'{letra} é uma vogal')
    else:
        print(f'{letra} é uma consoante')
verifica_alfabeto()

e é uma vogal


Para que serve o PIP no Python?

In [ ]:
# o PIP é uma espécie de gerenciador de pacotes onde por ele podemos instalar, remover e atualizar os pacotes que são geralmente utilizados 
# nos projetos em Python

%pip install nome do pacote # é a forma mais usada de instalar um pacote com o PIP

Crie um array com 10 números no formato float. Converta-os para o formato inteiro.

In [28]:
import numpy as np
exemplo_float = np.array([1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1, 10.1])
exemplo_float

array([ 1.1,  2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1])

In [29]:
exemplo_int = exemplo.astype(int)

In [30]:
exemplo_int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Converta o array abaixo para o formato booleano.
a = np.array([1,0,1],[1,1,1],[0,0,0])

In [31]:
a = np.array([[1,0,1],[1,1,1],[0,0,0]])

In [33]:
novo_a = a.astype(bool)
novo_a

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

Empilhe horizontalmente os arrays abaixo.
a = np.array([10,20,15],[0,0,20])
b = np.array([15,7,3],[5,5,8])

In [35]:
a = np.array([[10,20,15],[0,0,20]])
b = np.array([[15,7,3],[5,5,8]])

In [56]:
c = np.hstack((a, b))
c

array([[10, 20, 15, 15,  7,  3],
       [ 0,  0, 20,  5,  5,  8]])

Empilhe verticalmente os arrays do exercício acima.

In [54]:
c_vertical = np.vstack((a, b))

In [55]:
c_vertical

array([[10, 20, 15],
       [ 0,  0, 20],
       [15,  7,  3],
       [ 5,  5,  8]])

Gere uma lista de números inteiros que vão de 0 a 100, de 2 em 2, e, na sequência, converta essa lista em um array.

In [62]:
lista_1 = list(range(0, 102, 2))

In [64]:
array_lista_1 = np.asarray(lista_1)

In [65]:
array_lista_1

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Gere uma lista de valores que vão de 5 a 10 de 0.5 em 0.5.

In [74]:
lista_2 = np.arange(5, 10.5, 0.5)

In [75]:
lista_2

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

Crie um array 3x3 cujos valores seguem uma distribuição normal.

In [92]:
array_dist_normal = np.random.normal(3,3,9)
array_dist_normal = array_dist_normal.reshape(3, 3)
array_dist_normal

array([[-2.31768872,  4.01344983,  3.01237677],
       [ 5.13648999,  1.98530082,  2.14885197],
       [ 0.67916732,  3.35186101, -1.74382951]])

Como calcular o determinante de uma matriz no Numpy?

In [93]:
from numpy import linalg

In [94]:
np.linalg.det(array_dist_normal)

114.32562709717968